Repository labietelabiete/react-shopping-cart-context, pull requests merged in 2021-06, with the labels that each got.

#2 doc: contributors changed in readme file
  README.md
Labels: documentation

#5 Feat/create test folder
  .eslintrc.js
  package-lock.json
  src/test/index.js
  src/test/test.js
Labels: good first issue

#9 Feat/formik
  README.md
  src/App.js
  src/components/Cart/Cart.js
  src/context/checkoutData.js
  src/pages/CheckoutPages/PersonalDetails/PersonalDetails.js
  src/pages/CheckoutPages/PersonalDetails/PersonalDetailsSchema.js
Labels: enhancement

#11 Feat/formik inputs
  src/pages/CheckoutPages/PersonalDetails/PersonalDetails.js
  src/pages/CheckoutPages/PersonalDetails/PersonalDetails.scss
Labels: bug

#14 Feat/state reduce controll
  src/App.js
  src/context/checkoutData.js
  src/pages/CheckoutPages/PersonalDetails/PersonalDetails.js
  src/pages/CheckoutPages/PersonalDetails/PersonalDetailsSchema.js
Labels: bug

#15 Feat/state reduce controll
  src/App.js
  src/context/checkoutData.js
  src/pages/CheckoutPages/BillingAddress/BillingAddress.js
  src/pages/CheckoutPages/BillingAddress/BillingAddressSchema.js
  src/pages/CheckoutPages/OrderSummary/OrderSummary.js
  src/pages/CheckoutPages/PaymentDetails/PaymentDatailsSchema.js
  src/pages/CheckoutPages/PaymentDetails/PaymentDetails.js
  src/pages/CheckoutPages/PersonalDetails/PersonalDetails.js
Labels: enhancement

#20 Feat/overview sidebar
  src/components/OverviewSidebar/OverviewSidebar.js
  src/components/OverviewSidebar/index.js
  src/pages/CheckoutPages/BillingAddress/BillingAddress.js
  src/pages/CheckoutPages/PersonalDetails/PersonalDetails.js
Labels: good first issue

#18 Feat/order summary structure
  src/App.js
  src/pages/CheckoutPages/OrderSummary/OrderSummary.js
  src/pages/CheckoutPages/OrderSummary/OrderSummary.scss
  src/style.scss
Labels: enhancement

#22 Fix/summary alignment
  src/App.js
  src/pages/CheckoutPages/OrderSummary/OrderSummary.js
Labels: bug

#28 Feat/payment details page
  .eslintrc.js
  package-lock.json
  package.json
  src/App.js
  src/components/Cart/Cart.js
  src/components/Input/Input.js
  src/context/checkoutData.js
  src/img/applePay.png
  src/img/cardBack.png
  src/img/cardFront.png
  src/img/cardFront.svg
  src/img/cardFront1.png
  src/img/cardFront1.svg
  src/img/paypal.png
  src/img/visa.png
  src/pages/CheckoutPages/BillingAddress/BillingAddress.js
  src/pages/CheckoutPages/OrderSummary/OrderSummary.js
  src/pages/CheckoutPages/PaymentDetails/PaymentDatailsSchema.js
  src/pages/CheckoutPages/PaymentDetails/PaymentDetails.js
  src/pages/CheckoutPages/PaymentDetails/PaymentDetails.scss
  src/pages/CheckoutPages/PaymentDetails/PaymentDetailsSchema.js
  src/pages/CheckoutPages/PersonalDetails/PersonalDetails.js
Labels: enhancement

#32 Feat/protect card number
  package-lock.json
  package.json
  src/App.js
  src/components/Input/Input.js
  src/context/checkoutData.js
  src/img/amex.png
  src/img/gpay.png
  src/img/mastercard.PNG
  src/pages/CheckoutPages/OrderSummary/OrderSummary.js
  src/pages/CheckoutPages/PaymentDetails/PaymentDetails.js
  src/pages/CheckoutPages/PaymentDetails/PaymentDetails.scss
  src/pages/CheckoutPages/PaymentDetails/PaymentDetailsSchema.js
  src/style.scss
Labels: enhancement

#33 Feat/navbar
  package-lock.json
  package.json
  src/App.js
  src/components/Button/Button.js
  src/components/NavBar/NavBar.js
  src/components/NavBar/index.js
  src/components/OverviewSidebar/OverviewSidebar.scss
  src/components/SubHeader/SubHeader.js
  src/components/SubHeader/SubHeader.scss
  src/context/checkoutData.js
  src/pages/CheckoutPages/BillingAddress/BillingAddress.js
  src/pages/CheckoutPages/PaymentDetails/PaymentDetails.js
  src/pages/CheckoutPages/PersonalDetails/PersonalDetails.js
Labels: good first issue

#37 Fix labels
  package-lock.json
  src/components/Input/Input.js
  src/pages/CheckoutPages/PaymentDetails/PaymentDetails.js
Labels: bug

#38 Fix/payment method card view radio buttons
  src/App.js
  src/components/Input/Input.js
  src/context/checkoutData.js
  src/pages/CheckoutPages/PaymentDetails/PaymentDetails.js
Labels: bug

#40 fix: order summary page done
  src/pages/CheckoutPages/OrderSummary/OrderSummary.js
Labels: bug

#41 Fix/last minute
  src/components/Input/Input.js
  src/pages/CheckoutPages/OrderSummary/OrderSummary.js
  src/pages/CheckoutPages/PersonalDetails/PersonalDetails.js
  src/pages/CheckoutPages/PersonalDetails/PersonalDetailsSchema.js
Labels: bug
